version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ecommerce_backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ecommerce_backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ecommerce-frontend/Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
